#!/usr/bin/env python

import sys

def unCamelCase(s):
  result = ''
  for c in s:
    if c.isupper():
      result += '_'
    result += c.lower()
  return result

def camelCase(s):
  result = ''
  nextToUpper = 0
  for c in s:
    if c == '_':
      nextToUpper = 1
    elif nextToUpper:
      result += c.upper()
      nextToUpper = 0
    else:
      result += c
  return result

args = sys.argv[1:]

if len(args) == 0:
  print('Usage: %s [-u] names...' % (sys.argv[0]))
  sys.exit(1)

if args[0] == '-u':
  for arg in args[1:]:
    print(unCamelCase(arg))
else:
  for arg in args:
    print(camelCase(arg))
