#!/bin/bash

do_build() {
  # Whether to rebuild the gyp files.
  # Specify -f to rebuild them.
  REBUILD=false

  # Whether to display help.
  HELP=false

  while getopts fh opt; do
    case $opt in
      f) REBUILD=true;;
      h) HELP=true;;
    esac
    shift $((OPTIND - 1))
  done

  if $HELP; then
    echo "Usage: $0 [-f] [-h]"
    exit 0
  fi

  export BUILDTYPE=Debug
  export GYP_GENERATORS=ninja
  export GYP_PARALLEL=1

  if $REBUILD; then
    build/gyp_chromium
  fi

  targets="$@"
  if [ -z "$targets" ]; then
    targets="all"
  fi

  #base=out/Debug
  base=out/Release

  if [ -n "$RELEASE" ]; then
    base=out/Release
  elif [ -n "$DEBUG" ]; then
    base=out/Debug
  fi

  exec ninja -C $base -j512 $targets
}
