#!/bin/bash

do_build() {
  # Whether to rebuild the gyp files.
  # Specify -f to rebuild them.
  REBUILD=false

  # Whether to display help.
  HELP=false

  while getopts fh opt; do
    case $opt in
      f) REBUILD=true;;
      h) HELP=true;;
    esac
    shift $((OPTIND - 1))
  done

  if $HELP; then
    echo "Usage: $0 [-f] [-h]"
    exit 0
  fi

  if $REBUILD; then
    build/gyp_chromium #-D disable_nacl=1
  fi

  targets="$@"
  if [ -z "$targets" ]; then
    targets="chrome browser_tests sync_unit_tests unit_tests"
  fi

  exec make -j32 BUILDTYPE=Debug $targets
}
