#!/bin/bash

source "$HOME/.rc/scripts/crbuild"

#export GYP_DEFINES="clang=1                                        \
#                    remove_webcore_debug_symbols=1                 \
#                    fastbuild=1                                    \
#                    component=shared_library                       \
#                    safe_browsing=1                                \
#                    profiling=1                                    \
# asan=1                                                                       \
# linux_use_tcmalloc=0                                                         \
#                    release_extra_cflags=-fno-omit-frame-pointer   \
#                    buid_for_tool=memcheck                         \
# use_aura=1                                                                   \
#                    disable_pie=1                                  "

export GYP_DEFINES="\
  clang=1                                                                      \
  chromeos=1                                                                   \
  use_goma=1
  component=shared_library                                                     \
  "

# export GYP_DEFINES="\
#   clang=1                                                                      \
#   release_extra_cflags=\"-fno-omit-frame-pointer -g -O1 -fno-inline\"          \
#   component=shared_library                                                     \
# "

do_build "$@"
