#!/bin/bash

if [ -z "$@" ]; then
  echo "Usage: $0 '{\"xmpp_port\" ... }'"
  exit 1
fi

# E.g.
# {"xmpp_port": 52207, "port": 48674}

both_ports=`echo "$1" | sed 's/[^0-9,]//g'`
xmpp_port=`echo "$both_ports" | cut -f1 -d,`
port=`echo "$both_ports" | cut -f2 -d,`

# Shift past the xmpp args
shift

out/Debug/chrome \
  --enable-sync-extension-settings=true \
  --sync-url=http://127.0.0.1:${port}/chromiumsync \
  --enable-experimental-extension-apis \
  --sync-notification-method=p2p \
  --sync-notification-host=127.0.0.1:${xmpp_port} \
  --sync-allow-insecure-xmpp-connection \
  "$@"
