#!/bin/bash

. $HOME/.profile
LOGFILE="/tmp/crup.$$.log"

next_stage() {
  echo $@
  echo $@ >> $LOGFILE
}

run() {
  #$@ &>> $LOGFILE
  $@ >> $LOGFILE
  echo >> $LOGFILE
}

if [ `gcb` != master ]; then
  echo "Not on master branch, quitting."
  exit 1
fi

echo "Logging to $LOGFILE"
next_stage "Updating Chromium..."
run git pull # fetch
run git svn fetch
run git svn rebase

next_stage "Syncing deps..."
run crsync

VERSION="$1"
if [ -z "$VERSION" ]; then
  LKGR=`lkgr 2>/dev/null`
  VERSION=`git log --grep=src@$LKGR | head -n1 | cut -f2- -d' '`
fi
next_stage "Resetting to $VERSION..."
run git reset --hard "$VERSION"

next_stage "Done."
