#!/bin/bash

. $HOME/.profile
LOGFILE="/tmp/crup.$$.log"

next_stage() {
  echo $@
  echo $@ >> $LOGFILE
}

run() {
  $@ &>> $LOGFILE
  echo >> $LOGFILE
}

cdc
if [ `gcb` != master ]; then
  echo "Not on master branch, quitting."
  exit 1
fi

echo "Logging to $LOGFILE"
next_stage "Updating Chromium..."
run git fetch
run git svn fetch
run git svn rebase -l

VERSION="$1"
if [ -z "$VERSION" ]; then
  LKGR=`lkgr 2>/dev/null`
  VERSION=`git log --grep=src@$LKGR | head -n1 | cut -f2- -d' '`
fi
next_stage "Resetting to $VERSION..."
run git reset --hard "$VERSION"

next_stage "Syncing non-WebKit deps..."
run gclient sync -fDj 32

cdw
if [ `gcb` == gclient ]; then
  next_stage "Syncing WebKit..."
  run git fetch http://git.chromium.org/external/Webkit.git master
  run git fetch origin master
  #run git rebase master gclient
  run git rebase master
  cdc
  run tools/sync-webkit-git.py
  cdw
  run git reset --hard
else
  next_stage "Not syncing WebKit, not on gclient..."
fi

cdc
next_stage "Updating clang..."
run tools/clang/scripts/update.sh

next_stage "Done."
